version: "3"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    environment:
      - CSVSERVER_BORDER=${CSVSERVER_BORDER}
    volumes:
      - ./inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
